title: ABMI Species
version: 3.0
description: Information on species and habitats monitored by the Alberta Biodiversity Monitoring Institute.

url: http://sc-dev.abmi.ca
contents: http://species.abmi.ca/contents
ftproot: ftp://web|anonymous:anonymous@ftp.public.abmi.ca/species.abmi.ca

#permalink:   /:categories/:title.html
category: news

include: [".htaccess"]
exclude: ["rscripts","README.md","LICENSE.md","_scripts","NOTES.md"]
timezone: America/Edmonton

taxa:
  - title: Mammals
    url: /pages/species/mammals.html
    label: mammals
  - title: Birds
    url: /pages/species/birds.html
    label: birds
  - title: Soil mites
    url: /pages/species/mites.html
    label: mites
  - title: Vascular plants
    url: /pages/species/vplants.html
    label: vplants
  - title: Bryophytes
    url: /pages/species/mosses.html
    label: mosses
  - title: Lichens
    url: /pages/species/lichens.html
    label: lichens

