title: ABMI Species
version: '4.0 (2016-09-12)'
description: Information on species and habitats monitored by the Alberta Biodiversity Monitoring Institute.

show_sector: true
include_pager: true
# Bootswatch theme
bw_theme: lumen
bw_bg_col: default

baseurl: http://sc-dev.abmi.ca/development
#baseurl: http://species.abmi.ca
#contents: http://species.abmi.ca/contents
contents: http://species.abmi.ca/contents2
#ftproot: ftp://web|anonymous:anonymous@ftp.public.abmi.ca/species.abmi.ca
ftproot: http://ftp.public.abmi.ca/species.abmi.ca

#permalink:   /:categories/:title.html
#category: news

include: [".htaccess"]
exclude: ["rscripts","README.md","LICENSE.md","_scripts","NOTES.md"]
timezone: America/Edmonton

encoding: UTF-8
markdown: kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
markdown_ext: "markdown,mkdown,mkdn,mkd,md,Rmd"

# fancy fonts on/off
fancyfonts: false
# navbar style: inverse, transparent
navbar: transparent

taxa:
  - title: Mammals
    url: /pages/species/mammals.html
    label: mammals
  - title: Birds
    url: /pages/species/birds.html
    label: birds
  - title: Soil mites
    url: /pages/species/mites.html
    label: mites
  - title: Vascular plants
    url: /pages/species/vplants.html
    label: vplants
  - title: Bryophytes
    url: /pages/species/mosses.html
    label: mosses
  - title: Lichens
    url: /pages/species/lichens.html
    label: lichens

