title: ABMI Species
description: Information on species and habitats monitored by the Alberta Biodiversity Monitoring Institute.

show_sector: true
include_pager: true

# Bootswatch theme
bw_theme: cosmo
bw_bg_col: warning

## baseurl is either development or production
baseurl: http://sc-dev.abmi.ca/development
#baseurl: http://species.abmi.ca

## this is for hosting the figures within baseurl
#contents: http://species.abmi.ca/contents
contents: http://species.abmi.ca/contents/2017

## ftproot os the root of the ftp/html server that stores large files
#ftproot: ftp://web|anonymous:anonymous@ftp.public.abmi.ca/species.abmi.ca
ftproot: http://ftp.public.abmi.ca/species.abmi.ca

## species have there own thing, with some versioning
ftprootsp: http://ftp.public.abmi.ca/species.abmi.ca/species-2017

#permalink:   /:categories/:title.html
#category: news

include: [".htaccess"]
exclude: ["rscripts","README.md","LICENSE.md","_scripts","NOTES.md"]
timezone: America/Edmonton

encoding: UTF-8
markdown: kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
markdown_ext: "markdown,mkdown,mkdn,mkd,md,Rmd"

# fancy fonts on/off
fancyfonts: true
# navbar style: inverse, transparent
navbar: transparent

taxa:
  mammals:
    title: Mammals
    url: /pages/species/mammals.html
    label: mammals
    version: '5.0 (2017-07-13)'
  birds:
    title: Birds
    url: /pages/species/birds.html
    label: birds
    version: '4.1 (2017-07-13)'
  mites:
    title: Soil mites
    url: /pages/species/mites.html
    label: mites
    version: '5.0 (2017-07-13)'
  vplants:
    title: Vascular plants
    url: /pages/species/vplants.html
    label: vplants
    version: '5.0 (2017-07-13)'
  mosses:
    title: Bryophytes
    url: /pages/species/mosses.html
    label: mosses
    version: '5.0 (2017-07-13)'
  lichens:
    title: Lichens
    url: /pages/species/lichens.html
    label: lichens
    version: '5.0 (2017-07-13)'
